# -*- mode: ruby -*-
# vi: set ft=ruby :

hosts = {
  "host0" => {
    :os => "centos/7",
    :ip => "192.168.1.10"
  },
  "host1" => {
    :os => "centos/7",
    :ip => "192.168.1.11"
  },
  "host2" => {
    :os => "debian/jessie64",
    :ip => "192.168.1.12"
  }
}

ssh_pub_key = File.readlines("/home/user/.ssh/id_rsa.pub").first.strip

Vagrant.configure("2") do |config|
  hosts.each do |name, par|
    config.vm.define name do |machine|
      machine.vm.box = par[:os]
      machine.vm.hostname = "%s" % name
      machine.vm.network "public_network", bridge: "wlp2s0", ip: par[:ip]
      machine.vm.provider "virtualbox" do |v|
        v.name = name
        v.customize ["modifyvm", :id, "--memory", 256]
      end
      machine.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
        echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
        echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
      SHELL
    end
  end
end

